---
# This Playbook deploys Authentication/Authorization system

- hosts: auth
  vars_files:
    - vars/main.yml
    - vars/private.yml
  user: $global_user
  sudo: $global_use_sudo
  roles: 
    - {role: apt-update, when: auth_include_apt_update}
    - {role: ldap, when: auth_include_ldap}
    - {role: krb, when: auth_include_krb}
  handlers:
   - include: handlers/main.yml
