---
# This Playbook deploys ansible 

- hosts: auth
  vars_files:
    - vars/main.yml
    - vars/private.yml
  user: $global_user
  sudo: $global_use_sudo
  roles: 
    - {role: ldap, when: auth_include_ldap}
  tasks:
  - include: tasks/krb.yml
  - include: tasks/sssd.yml
  handlers:
   - include: handlers/main.yml
