---

- name: auth | sssd | Install sssd
  action: apt pkg=$item state=installed
  with_items:
    - sssd
  tags: 
    - sssd
    - auth

- name: auth | sssd | Ensure sssd.conf exists
  template: src=templates/etc/sssd/sssd.conf.j2 dest=/etc/sssd/sssd.conf owner=root group=root mode=0600
  tags: 
    - sssd
    - auth

- name: auth | sssd | Ensure sssd is started 
  service: name=sssd state=started
  tags: 
    - sssd
    - auth
