---

- name: ensure there is a ansible directory
  file: path=~root/.ansible state=directory owner=root group=root
  tags: ldap

#- name: Backup hosts file 
#  shell: cp /etc/hosts ~root/.ansible/ldap-etc-hosts creates=~root/.ansible/ldap-etc-hosts
#  tags: ldap

#- name: Copy over a temporary hosts file to configure correct distinguished name
#  template: src=templates/etc/hosts.j2 dest=/etc/hosts owner=root group=root
#  tags: ldap

- name: install ldap packages
  action: apt pkg=$item state=installed
  with_items:
    - slapd 
    - ldap-utils
    - ldapscripts 
  tags: ldap

#- name: Restore hosts file
#  shell: cp -v ~root/.ansible/ldap-etc-hosts /etc/hosts && touch ~root/.ansible/hosts-restored chdir=/tmp creates=~root/.ansible/hosts-restored

#- action: shell slappasswd -h {SSHA} -s $ldapPassword
#  register: hashedLdapPassword 

#- name: Copy over the change password ldif
#  template: src=templates/tmp/change_password.ldif.j2 dest=/tmp/change_password.ldif owner=root group=root
#  tags: ldap

#- name: Change password
#  shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f change_password.ldif && touch ~root/.ansible/change-password chdir=/tmp creates=~root/.ansible/change-password
#  tags: ldap

- name: Configure slapd
  dpkg_reconfigure: pkg=slapd answers='$FILE(files/dpkg-reconfigure/slapd)'

- name: Copy over the create users and group ldif 
  template: src=templates/tmp/create_users_and_groups.ldif.j2 dest=/tmp/create_users_and_groups.ldif owner=root group=root
  tags: ldap

- name: Install users and groups 
  shell: ldapadd -w $ldapPassword -x -D cn=admin,$dc -f create_users_and_groups.ldif && touch ~root/.ansible/create-users-and-groups chdir=/tmp creates=~root/.ansible/create-users-and-groups 
  tags: ldap

#- name: Install users and groups 
#  shell: ldapadd -Y EXTERNAL -H ldapi:/// -D cn=admin,$dc -f create_users_and_groups.ldif && touch ~root/.ansible/create-users-and-groups chdir=/tmp creates=~root/.ansible/create-users-and-groups 
#  tags: ldap

- name: Copy over the indexes ldif
  action: template src=templates/tmp/create_indexes.ldif.j2 dest=/tmp/create_indexes.ldif owner=root group=root
  tags: ldap

- name: Install indexes
  shell: ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f create_indexes.ldif && touch ~root/.ansible/create-indexes chdir=/tmp creates=~root/.ansible/create-indexes
  tags: ldap

- name: Copy over the autofs ldif
  action: template src=templates/tmp/create_autofs.ldif.j2 dest=/tmp/create_autofs.ldif owner=root group=root
  tags: ldap

- name: Install autofs
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f create_autofs.ldif && touch ~root/.ansible/create-autofs chdir=/tmp creates=~root/.ansible/create-autofs
  tags: ldap

- name: Copy over the automount ldif
  action: template src=templates/tmp/create_automount.ldif.j2 dest=/tmp/create_automount.ldif owner=root group=root
  tags: ldap

- name: Install automount
  shell: ldapadd -w $ldapPassword -x -D cn=admin,$dc -f create_automount.ldif && touch ~root/.ansible/create-automount chdir=/tmp creates=~root/.ansible/create-automount
  tags: ldap

#- name: Install automount
#  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f create_automount.ldif && touch ~root/.ansible/create-automount chdir=/tmp creates=~root/.ansible/create-automount
#  tags: ldap

- name: Copy over the sudo ldif
  action: template src=templates/tmp/create_sudo.ldif.j2 dest=/tmp/create_sudo.ldif owner=root group=root
  tags: ldap

- name: Install sudo
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f create_sudo.ldif && touch ~root/.ansible/create-sudo chdir=/tmp creates=~root/.ansible/create-sudo
  tags: ldap

- name: Copy over the sudo master ldif
  action: template src=templates/tmp/create_sudo_master.ldif.j2 dest=/tmp/create_sudo_master.ldif owner=root group=root
  tags: ldap

- name: Install sudo master
  shell: ldapadd -w $ldapPassword -x -D cn=admin,$dc -f create_sudo_master.ldif && touch ~root/.ansible/create-sudo-master chdir=/tmp creates=~root/.ansible/create-sudo-master
  tags: ldap


#- name: Install sudo master
#  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f create_sudo_master.ldif -D cn=admin,$dc && touch ~root/.ansible/create-sudo-master chdir=/tmp creates=~root/.ansible/create-sudo-master
#  tags: ldap

- name: ensure ldapscripts.conf exists
  template: src=templates/etc/ldapscripts/ldapscripts.conf.j2 dest=/etc/ldapscripts/ldapscripts.conf owner=root group=root
  tags: ldap

- name: ensure ldap.secret exists
  template: src=templates/etc/ldap.secret.j2 dest=/etc/ldap.secret owner=root group=root mode=0400
  tags: ldap

- name: ensure domainadmins exists
  template: src=templates/etc/sudoers.d/domainadmins dest=/etc/sudoers.d/domainadmins owner=root group=root mode=0440
  tags: ldap

# This is really goofy but editing the secrets file in vims leaves an extra space at the end. Not sure what all editors do this
# If your editor does not do this then this command will mess up your file.
- name: ensure ldap.secret has no trailing space
  command: truncate --size $ldapPasswordSize /etc/ldap.secret
